<textarea id="lead_generation_code" class="mt-20" placeholder="<?php echo __( 'Insert your code here', 'thrive-cb' ); ?>"></textarea>

<div class="tcb-modal-footer clearfix mt-20 control-grid">
	<div class="input fill">
		<button type="button" class="tcb-left tve-button grey click" data-fn="step" data-template="apis" data-next="0">
			<?php echo __( 'Switch to API Integration', 'thrive-cb' ); ?>
		</button>
	</div>
	<div class="input">
		<button type="button" class="tcb-right tve-button green click" data-fn="parseHTML">
			<?php echo __( 'Continue', 'thrive-cb' ); ?>
		</button>
	</div>
</div>
