<?php
/**
 * Created by PhpStorm.
 * User: Ovidiu
 * Date: 7/26/2018
 * Time: 1:14 PM
 */
?>
<span class="p-thumb p-global-thumb click" data-fn="color_click" data-color="<#= color #>" data-custom-name="<#= custom_name #>" data-name="<#= name #>" data-var="<#= global_prefix #><#= id #>" data-synced-var="<#= synced_var #>" data-id="<#= id #>">
	<span class="p-thumb-inner" style="<#= css_prop #>:var(<#= global_prefix #><#= id #>)"></span>
</span>
