<#if(typeof no_item !== 'undefined' && no_item){#>
<div class="list-no-items tcb-text-center"><?php echo __( 'None', 'thrive-cb' ) ?></div>
<#} else {#>
<div class="preview-list-item tcb-relative<#= (settings_icon = view.get_config( 'settings_icon', false )) ? '' : ' click'#>"
		data-fn="item_click" data-index="<#=item.index#>" data-label="<#=item.get('label')#>">
	<div class="item-icon"><#=item.get('icon')#></div>
	<div class="preview-list-sort-handle col-sep"><?php tcb_icon( 'dots2' ); ?></div>
	<div class="item-label tcb-truncate"><#=item.get('label')#></div>
	<# if (settings_icon = view.get_config( 'settings_icon', false )) { #>
	<a href="javascript:void(0)" data-side="left" data-tooltip="<?php esc_attr_e( 'Settings', 'thrive-cb' ) ?>" class="action-edit click" data-fn="item_click"
			data-index="<#=item.index#>">
		<#=TVE.icon(settings_icon)#>
	</a>
	<# } #>
	<# if (clone_icon = view.get_config( 'clone_icon', false )) { #>
	<a href="javascript:void(0)" data-tooltip="<?php esc_attr_e( 'Duplicate', 'thrive-cb' ) ?>" class="action-clone click" data-fn="item_duplicate"
			data-index="<#=item.index#>">
		<#=TVE.icon(clone_icon)#>
	</a>
	<# } #>
	<a href="javascript:void(0)" data-side="right" data-tooltip="<?php esc_attr_e( 'Remove', 'thrive-cb' ) ?>" class="action-remove click" data-fn="item_remove"
			data-index="<#=item.index#>">
		<?php tcb_icon( 'trash-light' ) ?>
	</a>
</div>
<#}#>
