<div class="control-grid">
	<label><?php echo __( 'Source', 'thrive-cb' ) ?></label>
	<select class="v-source change input" data-fn-change="show_section" data-fn-input="video_provider_changed">
		<option value=""><?php echo __( 'Select source', 'thrive-cb' ) ?></option>
		<option value="youtube">YouTube</option>
		<option value="vimeo">Vimeo</option>
		<option value="wistia">Wistia</option>
		<option value="custom">Custom</option>
	</select>
</div>


<div class="v-settings" style="display:none" id="v-settings-youtube" data-view="Youtube"><?php tcb_template( 'actions/responsive-video-providers/youtube' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-vimeo" data-view="Vimeo"><?php tcb_template( 'actions/responsive-video-providers/vimeo' ) ?></div>
<div class="v-settings" style="display:none" id="v-settings-wistia" data-view="Wistia"><?php tcb_template( 'actions/responsive-video-providers/wistia' ) ?></div>
<div class="v-settings tve_custom_responsive_video" style="display:none" id="v-settings-custom" data-view="Custom"><?php tcb_template( 'actions/responsive-video-providers/custom' ) ?></div>

<div class="control-grid responsive-video-time-label">
	<label>
		<?php echo __( 'Video Start Time', 'thrive-cb' ); ?>
	</label>
</div>

<div class="control-grid responsive-video-time-settings">
	<div class="tve-time-control" data-time="Minute"></div>
	<div class="tve-time-control" data-time="Second"></div>
</div>

<hr>
<div id="style-picker"></div>

<div class="tve-advanced-controls extend-grey">
	<div class="dropdown-header" data-prop="advanced">
		<span>
			<?php echo __( 'Advanced', 'thrive-cb' ); ?>
		</span>
	</div>
	<div class="dropdown-content clear-top">
		<p class="info-text tcb-hidden">
			<?php echo sprintf( __( 'Autoplay is not currently supported by default on mobile devices (tablets, phones). More info ', 'thrive-cb' ) ) ?>
			<a href="https://webkit.org/blog/6784/new-video-policies-for-ios/" target="_blank" rel="noopener" class="inline"><?php echo __( 'here', 'thrive-cb' ); ?></a>
			<?php echo sprintf( __( 'Autoplay will be muted by default on Chrome and Safari.', 'thrive-cb' ) ) ?>
		</p>

		<div class="r-v-checkbox-settings" id="r-v-checkbox-settings-youtube" data-setting="youtube"
			 style="display:none"><?php tcb_template( 'actions/responsive-video-providers/youtube-extra' ) ?></div>
		<div class="r-v-checkbox-settings" id="r-v-checkbox-settings-vimeo" data-setting="vimeo" style="display:none"><?php tcb_template( 'actions/responsive-video-providers/vimeo-extra' ) ?></div>
		<div class="r-v-checkbox-settings" id="r-v-checkbox-settings-wistia" data-setting="wistia" style="display:none"><?php tcb_template( 'actions/responsive-video-providers/wistia-extra' ) ?></div>
		<div class="r-v-checkbox-settings" id="r-v-checkbox-settings-custom" data-setting="custom" style="display:none"><?php tcb_template( 'actions/responsive-video-providers/custom-extra' ) ?></div>

		<div class="control-grid tcb-responsive-video-thumbnail wrap no-space">
			<label class="label full-width">
				<?php echo __( 'Video Thumbnail', 'thrive-cb' ); ?>
			</label>
			<div class="tve-video-thumbnail-control"></div>
		</div>
	</div>
</div>
