<div class="control-grid<#=this.get_extra_class()#>">
	<div class="label"><#= this.get_config( 'name' ) || this.get_config('label') #></div>
	<div class="input">
		<select class="tve-select change" data-fn="changed">
			<# _.each(this.get_options(), function(option) { #>
			<option class="tve-option" value="<#= option.value #>"
			<#= option.default? ' selected':'' #>><#= option.name #></option>
			<# }); #>
		</select>
	</div>
</div>
