<div class="control-grid">
	<div class="decoration-boxes">
		<div class="tve-decoration-side click top" data-fn="decorationSide" data-value="top"></div>
		<div class="tve-decoration-side click left" data-fn="decorationSide" data-value="left"></div>
		<div class="tve-decoration-side click right" data-fn="decorationSide" data-value="right"></div>
		<div class="tve-decoration-side click active bottom" data-fn="decorationSide" data-value="bottom"></div>
		<div class="tve-decoration-side disabled center" data-value=""></div>
	</div>
	<div class="decoration-type input">
		<select class="tve-select change tcb-base-divider-control" data-fn="chooseType">
			<option value="none"><?php echo __( 'None', 'thrive-cb' ) ?></option>
			<option value="slanted"><?php echo __( 'Slanted Edge', 'thrive-cb' ) ?></option>
			<option value="pointer"><?php echo __( 'Pointer', 'thrive-cb' ) ?></option>
			<option value="divider"><?php echo __( 'Divider', 'thrive-cb' ) ?></option>
			<option value="fancy_divider"><?php echo __( 'Fancy Divider', 'thrive-cb' ) ?></option>
		</select>
		<select class="tve-select change tcb-fancy-divider-control mt-10" data-fn="chooseFancyDivider">
			<option value="city_skyline"><?php echo __( 'City skyline', 'thrive-cb' ) ?></option>
			<option value="clouds"><?php echo __( 'Clouds', 'thrive-cb' ) ?></option>
			<option value="brush"><?php echo __( 'Brush', 'thrive-cb' ) ?></option>
			<option value="mini_waves"><?php echo __( 'Mini Waves', 'thrive-cb' ) ?></option>
			<option value="waves"><?php echo __( 'Waves', 'thrive-cb' ) ?></option>
			<option value="asymmetrical"><?php echo __( 'Asymmetrical', 'thrive-cb' ) ?></option>
		</select>
	</div>
</div>

<div class="tve-control tve-sub-control tve-slanted-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-pointer-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-divider-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-city-skyline-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-clouds-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-brush-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-mini-waves-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-waves-control" style="display:none"></div>
<div class="tve-control tve-sub-control tve-asymmetrical-control" style="display:none"></div>
